// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginForm(err string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-md mx-auto pt-16 rise\"><div class=\"mb-8\"><span class=\"grid place-items-center w-14 h-14 bg-lamp text-ink border border-ink shadow-hard mb-4\"><i data-lucide=\"lamp-desk\" class=\"w-7 h-7\"></i></span><h1 class=\"font-display text-3xl font-800 tracking-tight\">Entrar</h1><p class=\"text-muted text-sm mt-1.5\">Acesse suas provas e continue estudando.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if err != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"mb-5 border border-coral bg-coral/10 text-coral text-sm px-4 py-3 flex items-center gap-2 rise\"><i data-lucide=\"alert-circle\" class=\"w-4 h-4 shrink-0\"></i> <span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(err)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/auth.templ`, Line: 17, Col: 16}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form action=\"/login\" method=\"post\" class=\"space-y-4\"><label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Email</span> <input type=\"email\" name=\"email\" required autocomplete=\"email\" placeholder=\"voce@email.com\" class=\"input\"></label> <label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Senha</span> <input type=\"password\" name=\"password\" required autocomplete=\"current-password\" placeholder=\"••••••••\" class=\"input\"></label> <button type=\"submit\" class=\"btn-primary w-full px-6 py-3.5 text-sm uppercase tracking-[0.08em]\">Entrar <i data-lucide=\"arrow-right\" class=\"w-5 h-5\"></i></button></form><p class=\"text-center text-sm text-muted mt-3\">Não tem conta? <a href=\"/register\" class=\"text-lamp hover:underline font-700\">Criar agora</a></p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout(PageData{Title: "Entrar"}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func RegisterForm(err string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"max-w-md mx-auto pt-16 rise\"><div class=\"mb-8\"><span class=\"grid place-items-center w-14 h-14 bg-lamp text-ink border border-ink shadow-hard mb-4\"><i data-lucide=\"user-plus\" class=\"w-7 h-7\"></i></span><h1 class=\"font-display text-3xl font-800 tracking-tight\">Criar conta</h1><p class=\"text-muted text-sm mt-1.5\">Salve suas provas e estude quando quiser.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if err != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"mb-5 border border-coral bg-coral/10 text-coral text-sm px-4 py-3 flex items-center gap-2 rise\"><i data-lucide=\"alert-circle\" class=\"w-4 h-4 shrink-0\"></i> <span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(err)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/auth.templ`, Line: 62, Col: 16}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<form action=\"/register\" method=\"post\" class=\"space-y-4\"><label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Email</span> <input type=\"email\" name=\"email\" required autocomplete=\"email\" placeholder=\"voce@email.com\" class=\"input\"></label><div class=\"grid grid-cols-2 gap-4\"><label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Senha</span> <input type=\"password\" name=\"password\" required autocomplete=\"new-password\" placeholder=\"mín. 8 caracteres\" class=\"input\"></label> <label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Confirmar</span> <input type=\"password\" name=\"confirm\" required autocomplete=\"new-password\" placeholder=\"repita a senha\" class=\"input\"></label></div><button type=\"submit\" class=\"btn-primary w-full px-6 py-3.5 text-sm uppercase tracking-[0.08em]\">Criar conta <i data-lucide=\"arrow-right\" class=\"w-5 h-5\"></i></button></form><p class=\"text-center text-sm text-muted mt-5\">Você começa com 250.000 tokens.</p><p class=\"text-center text-sm text-muted mt-6\">Já tem conta? <a href=\"/login\" class=\"text-lamp hover:underline font-700\">Entrar</a></p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout(PageData{Title: "Criar conta"}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
