// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"learnix/internal/db"
	"learnix/internal/mindmap"
)

func mindMapJSON(graph mindmap.Graph) string {
	b, _ := mindmap.Encode(graph)
	return string(b)
}

func MindMapPage(topic string, studyID int64, graph mindmap.Graph, user *db.User, q *db.Quota, isAdmin bool, csrf string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"max-w-[1500px] mx-auto px-4 sm:px-6 pb-24\"><div class=\"flex flex-wrap items-center justify-between gap-4 py-5\"><div class=\"min-w-0\"><div class=\"flex items-center gap-2 text-xs text-muted mb-2\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(studyBase(studyID) + "/workspace")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/mindmap.templ`, Line: 19, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"hover:text-lamp transition\">Estudo</a> <i data-lucide=\"chevron-right\" class=\"w-3.5 h-3.5\"></i> <span class=\"text-lamp\">Mapa mental</span></div><h1 class=\"font-display text-3xl sm:text-4xl font-800 tracking-tight\">Mapa mental</h1><p class=\"text-sm text-muted mt-1\">Navegue pelo conteúdo, recolha ramos e ajuste o mapa enquanto estuda.</p></div><div class=\"flex items-center gap-2\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinURLErrs(studyBase(studyID) + "/workspace")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/mindmap.templ`, Line: 27, Col: 48}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"btn-secondary px-3 py-2 text-sm font-800\"><i data-lucide=\"arrow-left\" class=\"w-4 h-4\"></i> Voltar</a> <button type=\"button\" data-map-save class=\"btn-primary px-3 py-2 text-sm\"><i data-lucide=\"save\" class=\"w-4 h-4\"></i> Salvar</button></div></div><div class=\"mb-4 flex items-start gap-3 border border-lamp bg-lamp/10 px-4 py-3 text-xs text-cream/80\" role=\"status\"><i data-lucide=\"flask-conical\" class=\"mt-0.5 h-4 w-4 shrink-0 text-lamp\"></i><p><strong class=\"font-800 text-lamp\">Recurso experimental.</strong> O mapa mental ainda está em desenvolvimento e pode mudar.</p></div><section id=\"mind-map-app\" data-map-json=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(mindMapJSON(graph))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/mindmap.templ`, Line: 40, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" data-map-update-url=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(studyBase(studyID) + "/mapa-mental")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/mindmap.templ`, Line: 41, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" data-map-csrf=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(csrf)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/mindmap.templ`, Line: 42, Col: 24}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"grid lg:grid-cols-[minmax(0,1fr)_20rem] gap-4 ui-panel p-3 sm:p-4\"><div class=\"min-h-[560px] border border-line bg-ink overflow-hidden\" data-map-viewport tabindex=\"0\" aria-label=\"Mapa mental interativo\"><svg class=\"block w-full h-full min-h-[560px]\" data-map-svg role=\"img\" aria-label=\"Mapa mental\"></svg></div><aside class=\"border border-line bg-surface2 p-4 flex flex-col min-h-[560px]\"><div class=\"flex items-center justify-between gap-2\"><h2 class=\"font-display text-xl font-800\">Nó selecionado</h2><span data-map-status class=\"text-[11px] text-muted\">Pronto</span></div><div class=\"mt-4 space-y-3\" data-map-inspector></div><div class=\"mt-auto pt-4 border-t border-line space-y-2\"><button type=\"button\" data-map-add aria-label=\"Escolher pai para novo ramo\" class=\"w-full inline-flex items-center justify-center gap-2 border border-lamp bg-lamp/10 px-3 py-2 text-sm font-800 text-lamp hover:bg-lamp/20 transition\"><i data-lucide=\"plus\" class=\"w-4 h-4\"></i><span data-map-add-label>Adicionar ramo</span></button> <button type=\"button\" data-map-remove class=\"w-full inline-flex items-center justify-center gap-2 border border-coral bg-coral/5 px-3 py-2 text-sm font-800 text-coral hover:bg-coral/10 transition\"><i data-lucide=\"trash-2\" class=\"w-4 h-4\"></i>Remover subárvore</button><p class=\"text-[11px] leading-relaxed text-muted\">Arraste o fundo para navegar. Use a roda ou os botões para zoom. Clique em um nó para editar. Para criar um ramo, escolha explicitamente o nó pai.</p></div></aside></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout(studyPageData("Mapa mental", "study", topic, user, q, isAdmin, studyID, MobileStudyState{})).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
