// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"net/url"
	"strings"
	"time"

	"learnix/internal/db"
)

func profileURL(slug string) string {
	return "/profile/" + url.PathEscape(slug)
}

func profileAvatarURL(slug string) string {
	return profileURL(slug) + "/avatar"
}

func profileScore(cents int64) string {
	return strings.ReplaceAll(fmt.Sprintf("%.2f", float64(cents)/100), ".", ",")
}

func profilePercent(cents int64) string {
	return strings.ReplaceAll(fmt.Sprintf("%.2f", float64(cents)/100), ".", ",") + "%"
}

func profileRankClasses(key string) string {
	switch key {
	case "bronze":
		return "text-[#d69a61] bg-[#d69a61]/10 border-[#d69a61]/30"
	case "prata":
		return "text-[#c8d0d9] bg-[#c8d0d9]/10 border-[#c8d0d9]/30"
	case "ouro":
		return "text-lamp bg-lamp/10 border-lamp/30"
	case "token-maxxer":
		return "text-coral bg-coral/10 border-coral/30"
	case "knowledge-maxer":
		return "text-lamp bg-lamp/10 border-lamp"
	case "study-maxer":
		return "text-[#f7c948] bg-[#f7c948]/10 border-[#f7c948]/30"
	default:
		return "text-muted bg-surface2 border-line"
	}
}

func profileUsernameStatus(profile db.Profile) string {
	if profile.CanChangeUsername(time.Now().UTC()) {
		return "Disponível para troca neste mês."
	}
	last := profile.SlugChangedAt.UTC()
	next := time.Date(last.Year(), last.Month(), 1, 0, 0, 0, 0, time.UTC).AddDate(0, 1, 0)
	return "Próxima troca em " + next.Format("02/01/2006") + "."
}

func profileStatFields() []db.ProfileVisibilityField {
	var fields []db.ProfileVisibilityField
	for _, field := range db.ProfileVisibilityFields() {
		switch field.Key {
		case db.ProfileVisibilityDisplayName, db.ProfileVisibilityAvatar, db.ProfileVisibilityBio,
			db.ProfileVisibilityRank, db.ProfileVisibilityAverageScore:
			continue
		default:
			fields = append(fields, field)
		}
	}
	return fields
}

func profileStatValue(profile db.ProfileView, key string) string {
	stats := profile.Stats
	switch key {
	case db.ProfileVisibilityRankedQuizzes:
		return fmtTokens(stats.RankedQuizCount)
	case db.ProfileVisibilityQuizzesCompleted:
		return fmtTokens(stats.QuizzesCompleted)
	case db.ProfileVisibilityQuizzesStarted:
		return fmtTokens(stats.QuizzesStarted)
	case db.ProfileVisibilityStudiesCreated:
		return fmtTokens(stats.StudiesCreated)
	case db.ProfileVisibilityStudyResets:
		return fmtTokens(stats.StudyResets)
	case db.ProfileVisibilityQuestionsAnswered:
		return fmtTokens(stats.QuestionsAnswered)
	case db.ProfileVisibilityCorrectAnswers:
		return fmtTokens(stats.CorrectAnswers)
	case db.ProfileVisibilityAccuracy:
		if stats.QuestionsAnswered == 0 {
			return "—"
		}
		return profilePercent(stats.AccuracyCents)
	case db.ProfileVisibilityDiagnosticsSubmitted:
		return fmtTokens(stats.DiagnosticsSubmitted)
	case db.ProfileVisibilityChatTurns:
		return fmtTokens(stats.ChatTurns)
	case db.ProfileVisibilityAICalls:
		return fmtTokens(stats.AICalls)
	case db.ProfileVisibilityTokensUsed:
		return fmtTokens(stats.TokensUsed)
	case db.ProfileVisibilityGenerationFailures:
		return fmtTokens(stats.QuizGenerationFailures)
	default:
		return "—"
	}
}

func ProfilePage(data PageData, profile db.ProfileView, owner bool, csrf, notice string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"{ editing: false }\" @keydown.escape.window=\"editing = false\" class=\"pt-8 max-w-5xl mx-auto\"><div class=\"flex flex-col sm:flex-row sm:items-end justify-between gap-5 rise\"><div class=\"flex items-center gap-4 min-w-0\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if profile.Visible(db.ProfileVisibilityAvatar, owner) && len(profile.Details.AvatarData) > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<img src=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(profileAvatarURL(profile.Profile.Slug))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 113, Col: 55}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" alt=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue("Foto de " + profile.PublicName(owner))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 113, Col: 102}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" class=\"w-20 h-20 rounded-none object-cover border border-line shadow-hard shrink-0\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<span class=\"grid place-items-center w-20 h-20 bg-lamp text-ink border border-ink shadow-hard shrink-0\"><i data-lucide=\"user-round\" class=\"w-9 h-9\"></i></span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"min-w-0\"><span class=\"micro-label inline-flex items-center gap-2 bg-surface border border-line px-3 py-1.5 text-cream mb-3\"><i data-lucide=\"id-card\" class=\"w-3.5 h-3.5 text-lamp\"></i> Perfil público</span><h1 class=\"font-display text-4xl sm:text-5xl font-800 tracking-tight truncate\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(profile.PublicName(owner))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 125, Col: 112}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</h1><p class=\"text-muted text-sm mt-1.5 truncate\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(profile.Profile.Slug)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 126, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if owner {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<button type=\"button\" @click=\"editing = true\" class=\"btn-primary px-4 py-3 text-sm uppercase tracking-[0.08em]\"><i data-lucide=\"pencil\" class=\"w-4 h-4\"></i> Editar perfil</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if notice != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"mt-6 rounded-none border border-lamp bg-lamp/10 text-lamp text-sm px-4 py-3 flex items-center gap-2 pop\"><i data-lucide=\"check-circle\" class=\"w-4 h-4 shrink-0\"></i> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(notice)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 141, Col: 13}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<div class=\"grid lg:grid-cols-[1.15fr_.85fr] gap-4 mt-10\"><section class=\"ui-panel-flat p-6 sm:p-8 rise\"><div class=\"micro-label text-muted mb-4\"><i data-lucide=\"quote\" class=\"w-3.5 h-3.5 text-lamp\"></i> Sobre</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if profile.Visible(db.ProfileVisibilityBio, owner) && strings.TrimSpace(profile.Details.Bio) != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<p class=\"text-cream/90 leading-relaxed whitespace-pre-wrap\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(profile.Details.Bio)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 152, Col: 88}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<p class=\"text-muted text-sm\">Este perfil ainda não tem uma bio pública.</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "</section><section class=\"ui-panel-flat p-6 sm:p-8 rise\" style=\"animation-delay:.08s\"><div class=\"flex items-center justify-between gap-3 mb-5\"><div class=\"micro-label text-muted\"><i data-lucide=\"trophy\" class=\"w-3.5 h-3.5 text-lamp\"></i> Rank</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if profile.Visible(db.ProfileVisibilityRank, owner) {
				var templ_7745c5c3_Var9 = []any{"inline-flex items-center rounded-none border px-3 py-1 text-xs font-800", profileRankClasses(profile.Rank.Key)}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var9...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<span class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var10 string
				templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var9).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var11 string
				templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(profile.Rank.Label)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 165, Col: 155}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if profile.Visible(db.ProfileVisibilityRank, owner) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "<p class=\"font-display text-3xl font-800\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var12 string
				templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(profile.Rank.Label)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 169, Col: 68}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if profile.Rank.QuizCount < 5 {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "<p class=\"text-muted text-xs mt-2\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var13 string
					templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(fmtTokens(5 - profile.Rank.QuizCount))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 171, Col: 79}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " quizzes ranqueados até a próxima avaliação.</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "<p class=\"text-muted text-sm\">Rank oculto pelo dono do perfil.</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if profile.Visible(db.ProfileVisibilityAverageScore, owner) {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<div class=\"mt-6 pt-5 border-t border-line flex items-end justify-between gap-4\"><span class=\"text-xs text-muted\">Média ranqueada</span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if profile.Rank.QuizCount > 0 {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "<strong class=\"font-display text-2xl text-lamp\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var14 string
					templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(profileScore(profile.Rank.AverageScoreCents))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 180, Col: 102}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</strong>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "<strong class=\"font-display text-2xl text-muted\">—</strong>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, "</section></div><section class=\"mt-10 rise\" style=\"animation-delay:.12s\"><div class=\"flex items-end justify-between gap-4 mb-5\"><div><span class=\"micro-label inline-flex items-center gap-2 bg-surface border border-line px-3 py-1.5 text-cream mb-3\"><i data-lucide=\"bar-chart-3\" class=\"w-3.5 h-3.5 text-lamp\"></i> Estatísticas</span><h2 class=\"font-display text-2xl sm:text-3xl font-800 tracking-tight\">Ritmo de aprendizado</h2></div></div><div class=\"grid sm:grid-cols-2 lg:grid-cols-4 gap-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, field := range profileStatFields() {
				if profile.Visible(field.Key, owner) {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "<div class=\"ui-panel-flat p-4\"><p class=\"text-[11px] uppercase tracking-[0.12em] text-muted truncate\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var15 string
					templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(field.Label)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 203, Col: 92}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</p><p class=\"font-display text-2xl font-800 text-cream mt-2\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var16 string
					templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(profileStatValue(profile, field.Key))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 204, Col: 104}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "</p></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "</div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if owner {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "<div x-show=\"editing\" x-cloak class=\"fixed inset-0 z-50 grid place-items-center bg-ink/95 p-4\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Editar perfil\"><div @click.outside=\"editing = false\" class=\"w-full max-w-2xl max-h-[90vh] overflow-y-auto ui-panel p-6 sm:p-8 pop\"><div class=\"flex items-start justify-between gap-4 mb-6\"><div><h2 class=\"font-display text-2xl font-800\">Editar perfil</h2><p class=\"text-muted text-sm mt-1\">Escolha o que a comunidade pode ver.</p></div><button type=\"button\" @click=\"editing = false\" class=\"grid place-items-center w-9 h-9 border border-line text-muted hover:text-cream hover:bg-surface2 transition\" aria-label=\"Fechar\"><i data-lucide=\"x\" class=\"w-4 h-4\"></i></button></div><form action=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var17 templ.SafeURL
				templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinURLErrs(profileURL(profile.Profile.Slug))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 223, Col: 53}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "\" method=\"post\" enctype=\"multipart/form-data\" class=\"space-y-5\"><input type=\"hidden\" name=\"csrf\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var18 string
				templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.ResolveAttributeValue(csrf)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 224, Col: 52}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var18)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "\"><div class=\"grid sm:grid-cols-[auto_1fr] gap-5 items-center\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if len(profile.Details.AvatarData) > 0 {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "<img src=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var19 string
					templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.ResolveAttributeValue(profileAvatarURL(profile.Profile.Slug))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 227, Col: 58}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var19)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "\" alt=\"Sua foto atual\" class=\"w-20 h-20 rounded-none object-cover border border-line\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "<span class=\"grid place-items-center w-20 h-20 rounded-none bg-surface2 text-muted border border-line\"><i data-lucide=\"user-round\" class=\"w-8 h-8\"></i></span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "<div class=\"space-y-2\"><label class=\"block text-xs font-700 text-muted\">Nova foto <input type=\"file\" name=\"avatar\" accept=\"image/png,image/jpeg,image/webp\" class=\"block mt-1.5 text-sm text-cream file:mr-3 file:rounded-none file:border-0 file:bg-lamp/15 file:text-lamp file:px-3 file:py-1.5 file:font-700\"></label> <label class=\"inline-flex items-center gap-2 text-xs text-muted\"><input type=\"checkbox\" name=\"remove_avatar\" class=\"accent-lamp\"> Remover foto atual</label></div></div><label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Usuário público</span> <input type=\"text\" name=\"username\" maxlength=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var20 string
				templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", db.PublicUsernameMaxLength))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 238, Col: 100}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var20)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var21 string
				templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.ResolveAttributeValue(profile.Profile.Username)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 238, Col: 135}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var21)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "\" placeholder=\"seu-usuario\" autocomplete=\"username\" class=\"input\"><p class=\"text-[11px] text-muted mt-1.5\">Atual: <strong class=\"text-cream/80\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var22 string
				templ_7745c5c3_Var22, templ_7745c5c3_Err = templ.JoinStringErrs(profile.Profile.Slug)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 239, Col: 108}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var22))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "</strong> · ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var23 string
				templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.JoinStringErrs(profileUsernameStatus(profile.Profile))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 239, Col: 163}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var23))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 47, "</p></label> <label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Nome público</span><input type=\"text\" name=\"display_name\" maxlength=\"60\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var24 string
				templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.ResolveAttributeValue(profile.Details.DisplayName)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 241, Col: 192}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var24)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 48, "\" placeholder=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var25 string
				templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.ResolveAttributeValue(profile.Profile.Slug)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 241, Col: 229}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var25)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 49, "\" class=\"input\"></label> <label class=\"block\"><span class=\"text-xs font-700 text-muted mb-1.5 block\">Bio</span><textarea name=\"bio\" maxlength=\"280\" rows=\"4\" placeholder=\"Conte um pouco sobre sua jornada de estudos...\" class=\"input resize-none\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var26 string
				templ_7745c5c3_Var26, templ_7745c5c3_Err = templ.JoinStringErrs(profile.Details.Bio)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 242, Col: 247}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var26))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 50, "</textarea></label><div><p class=\"text-xs font-700 text-muted mb-2\">Campos visíveis</p><div class=\"grid sm:grid-cols-2 gap-2 border border-line bg-ink p-3\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, field := range db.ProfileVisibilityFields() {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 51, "<label class=\"flex items-center gap-2 px-2 py-1.5 text-xs text-cream/80 hover:bg-surface2 transition\"><input type=\"checkbox\" name=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var27 string
					templ_7745c5c3_Var27, templ_7745c5c3_Err = templ.ResolveAttributeValue("visible_" + field.Key)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 247, Col: 164}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var27)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 52, "\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					if profile.Details.Visibility[field.Key] {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 53, " checked")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 54, " class=\"accent-lamp\"> ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var28 string
					templ_7745c5c3_Var28, templ_7745c5c3_Err = templ.JoinStringErrs(field.Label)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/components/profile.templ`, Line: 247, Col: 253}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var28))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 55, "</label>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 56, "</div></div><div class=\"flex justify-end gap-2 pt-2\"><button type=\"button\" @click=\"editing = false\" class=\"btn-secondary px-4 py-2.5 text-sm\">Cancelar</button> <button type=\"submit\" class=\"btn-primary px-4 py-2.5 text-sm\"><i data-lucide=\"save\" class=\"w-4 h-4\"></i> Salvar perfil</button></div></form></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 57, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout(data).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
